name: maya-ph-sdk

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run tests
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_KEY }}
          SECRET_TOKEN: ${{ secrets.SECRET_KEY }}
          NUMBER: ${{ secrets.NUMBER }}
          CVC: ${{ secrets.CVC }}
          EXP_YEAR: ${{ secrets.EXP_YEAR }}
          EXP_MONTH: ${{ secrets.EXP_MONTH }}
        run: cargo test --verbose
